# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Fashion_MNIST_Project',
                'doc_host': 'https://nvtai040502.github.io',
                'git_url': 'https://github.com/nvtai040502/Fashion_MNIST_Project',
                'lib_path': 'Fashion_MNIST_Project'},
  'syms': {'Fashion_MNIST_Project.core': {'Fashion_MNIST_Project.core.foo': ('core.html#foo', 'Fashion_MNIST_Project/core.py')}}}
